data = [{
    "first_name": "Emily",
    "last_name": "Clark",
    "email": "emily.clark@example.com",
    "phone_number": "555-111-2222",
    "company": "TechSolutions Inc.",
    "position": "Graphic Designer",
    "location": "San Francisco, CA",
    "notes": "Emily is a skilled Graphic Designer at TechSolutions Inc. Our recent collaborations have focused on creating visually appealing designs for our marketing materials and website. Emily prefers direct messaging for quick updates on design projects and enjoys attending design conferences. She has expertise in graphic design, user interface design, and brand identity. Emily's creativity and attention to detail significantly contribute to the visual appeal of our products.",
    "meeting_history": ["2022-06-01", "2022-06-15", "2022-07-01"],
    "category": "team member"
},
    {
        "first_name": "Emma",
        "last_name": "Johnson",
        "email": "emma.johnson@example.com",
        "phone_number": "555-111-2222",
        "company": "TechSolutions Inc.",
        "position": "Software Developer",
        "location": "San Francisco, CA",
        "notes": "Emma is a talented Software Developer at TechSolutions Inc. Our recent collaborations have focused on implementing cutting-edge features in our software products. Emma prefers email communication for project updates and enjoys discussing the latest trends in software development. She has expertise in full-stack development, UI/UX design, and agile methodologies. Emma's proactive approach and innovative ideas significantly contribute to the success of our projects.",
        "meeting_history": ["2022-04-01", "2022-04-15", "2022-05-01"],
        "category": "current client"
    },
    {
        "first_name": "Daniel",
        "last_name": "Williams",
        "email": "daniel.williams@example.com",
        "phone_number": "555-333-4444",
        "company": "InnovateTech Solutions",
        "position": "Data Scientist",
        "location": "New York, NY",
        "notes": "Daniel is a skilled Data Scientist at InnovateTech Solutions. Our recent discussions have revolved around leveraging data for business insights and decision-making. Daniel prefers scheduled video calls for in-depth data analysis discussions and enjoys attending data science conferences. He has expertise in machine learning, statistical analysis, and data visualization. Daniel's analytical skills and attention to detail significantly contribute to the success of our data-driven projects.",
        "meeting_history": ["2022-04-05", "2022-04-20", "2022-05-05"],
        "category": "potential client"
    },
    {
        "first_name": "Olivia",
        "last_name": "Smith",
        "email": "olivia.smith@example.com",
        "phone_number": "555-555-6666",
        "company": "InnoTech Innovations",
        "position": "Product Manager",
        "location": "Seattle, WA",
        "notes": "Olivia serves as a Product Manager at InnoTech Innovations. Our recent collaborations have involved product strategy and feature planning. Olivia prefers direct messaging for quick updates and enjoys participating in product management workshops. She has expertise in product development, roadmap planning, and user experience design. Olivia's strategic mindset and user-centric approach significantly contribute to the success of our products.",
        "meeting_history": ["2022-04-10", "2022-04-25", "2022-05-10"],
        "category": "team member"
    },
    {
        "first_name": "William",
        "last_name": "Brown",
        "email": "william.brown@example.com",
        "phone_number": "555-777-8888",
        "company": "TechGenius Solutions",
        "position": "IT Consultant",
        "location": "Chicago, IL",
        "notes": "William is an experienced IT Consultant at TechGenius Solutions. Our recent discussions have focused on optimizing IT infrastructure for efficiency. William prefers email communication for strategic planning updates and enjoys attending technology conferences. He has expertise in IT consulting, cybersecurity, and cloud solutions. William's technical insights and problem-solving skills significantly contribute to the success of our IT projects.",
        "meeting_history": ["2022-04-15", "2022-04-30", "2022-05-15"],
        "category": "manager"
    },
    {
        "first_name": "Ava",
        "last_name": "Jones",
        "email": "ava.jones@example.com",
        "phone_number": "555-999-0000",
        "company": "Digital Solutions Co.",
        "position": "Digital Marketing Specialist",
        "location": "Los Angeles, CA",
        "notes": "Ava is a Digital Marketing Specialist at Digital Solutions Co. Our recent collaborations have focused on digital marketing strategies and campaign optimization. Ava prefers scheduled video calls for in-depth marketing discussions and enjoys attending marketing conferences. She has expertise in digital marketing, social media strategy, and online advertising. Ava's creative ideas and data-driven approach significantly contribute to the success of our digital marketing campaigns.",
        "meeting_history": ["2022-04-20", "2022-05-05", "2022-05-20"],
        "category": "blacklisted"
    },
{
    "first_name": "Ryan",
    "last_name": "Taylor",
    "email": "ryan.taylor@example.com",
    "phone_number": "555-333-4444",
    "company": "InnovateTech Solutions",
    "position": "HR Specialist",
    "location": "New York, NY",
    "notes": "Ryan serves as an HR Specialist at InnovateTech Solutions. Our recent discussions have revolved around talent acquisition, employee engagement, and HR policy development. Ryan prefers scheduled video calls for in-depth HR strategy discussions and enjoys attending HR conferences. He has expertise in human resources management, talent acquisition, and employee relations. Ryan's interpersonal skills and strategic HR thinking significantly contribute to the success of our HR initiatives.",
    "meeting_history": ["2022-06-05", "2022-06-20", "2022-07-05"],
    "category": "team member"
},
{
    "first_name": "Sophia",
    "last_name": "Turner",
    "email": "sophia.turner@example.com",
    "phone_number": "555-555-6666",
    "company": "InnoTech Innovations",
    "position": "Graphic Designer",
    "location": "Seattle, WA",
    "notes": "Sophia is a creative Graphic Designer at InnoTech Innovations. Our recent collaborations have involved designing engaging visuals for our marketing campaigns and product presentations. Sophia prefers direct messaging for quick updates on design projects and enjoys attending graphic design workshops. She has expertise in graphic design, illustration, and multimedia arts. Sophia's artistic flair and design sensibility significantly contribute to the visual identity of our brand.",
    "meeting_history": ["2022-06-10", "2022-06-25", "2022-07-10"],
    "category": "team member"
},
{
    "first_name": "Alex",
    "last_name": "Parker",
    "email": "alex.parker@example.com",
    "phone_number": "555-777-8888",
    "company": "TechGenius Solutions",
    "position": "HR Specialist",
    "location": "Chicago, IL",
    "notes": "Alex is an HR Specialist at TechGenius Solutions. Our recent discussions have focused on employee development, workplace culture, and HR policy enhancements. Alex prefers email communication for updates on HR initiatives and enjoys attending HR and leadership conferences. They have expertise in human resources management, talent development, and employee engagement. Alex's dedication to fostering a positive workplace culture significantly contributes to the success of our HR initiatives.",
    "meeting_history": ["2022-06-15", "2022-06-30", "2022-07-15"],
    "category": "team member"
},
{
    "first_name": "Ethan",
    "last_name": "Miller",
    "email": "ethan.miller@example.com",
    "phone_number": "555-999-0000",
    "company": "Digital Solutions Co.",
    "position": "Graphic Designer",
    "location": "Los Angeles, CA",
    "notes": "Ethan is a creative Graphic Designer at Digital Solutions Co. Our recent collaborations have focused on designing impactful visuals for our digital marketing campaigns and web design projects. Ethan prefers scheduled video calls for in-depth design discussions and enjoys attending graphic design conferences. He has expertise in graphic design, branding, and digital illustration. Ethan's artistic vision and design expertise significantly contribute to the success of our visual communications.",
    "meeting_history": ["2022-06-20", "2022-07-05", "2022-07-20"],
    "category": "team member"
},  {
    "first_name": "Emma",
    "last_name": "Johnson",
    "email": "emma.johnson@example.com",
    "phone_number": "555-111-2222",
    "company": "TechSolutions Inc.",
    "position": "Digital Marketing Specialist",
    "location": "San Francisco, CA",
    "notes": "Emma is a talented Digital Marketing Specialist at TechSolutions Inc. Our recent collaborations have focused on creating effective digital marketing strategies and optimizing online campaigns. Emma prefers scheduled video calls for in-depth marketing discussions and enjoys attending marketing conferences. She has expertise in digital marketing, social media strategy, and online advertising. Emma's creative ideas and data-driven approach significantly contribute to the success of our digital marketing initiatives.",
    "meeting_history": ["2022-04-01", "2022-04-15", "2022-05-01"],
    "category": "potential client"
  },
  {
    "first_name": "Daniel",
    "last_name": "Williams",
    "email": "daniel.williams@example.com",
    "phone_number": "555-333-4444",
    "company": "InnovateTech Solutions",
    "position": "Digital Marketing Specialist",
    "location": "New York, NY",
    "notes": "Daniel is a skilled Digital Marketing Specialist at InnovateTech Solutions. Our recent discussions have revolved around creating impactful digital marketing campaigns and optimizing online presence. Daniel prefers scheduled video calls for in-depth marketing strategy discussions and enjoys attending digital marketing conferences. He has expertise in digital marketing analytics, search engine optimization, and online brand building. Daniel's analytical skills and strategic thinking significantly contribute to the success of our digital marketing efforts.",
    "meeting_history": ["2022-04-05", "2022-04-20", "2022-05-05"],
    "category": "potential client"
  },
  {
    "first_name": "Olivia",
    "last_name": "Smith",
    "email": "olivia.smith@example.com",
    "phone_number": "555-555-6666",
    "company": "InnoTech Innovations",
    "position": "Digital Marketing Specialist",
    "location": "Seattle, WA",
    "notes": "Olivia serves as a Digital Marketing Specialist at InnoTech Innovations. Our recent collaborations have involved creating innovative digital marketing strategies and enhancing online visibility. Olivia prefers direct messaging for quick updates on marketing campaigns and enjoys attending digital marketing workshops. She has expertise in digital advertising, social media marketing, and content creation. Olivia's strategic mindset and creativity significantly contribute to the success of our digital marketing projects.",
    "meeting_history": ["2022-04-10", "2022-04-25", "2022-05-10"],
    "category": "potential client"
  },
  {
    "first_name": "William",
    "last_name": "Brown",
    "email": "william.brown@example.com",
    "phone_number": "555-777-8888",
    "company": "TechGenius Solutions",
    "position": "Digital Marketing Specialist",
    "location": "Chicago, IL",
    "notes": "William is an experienced Digital Marketing Specialist at TechGenius Solutions. Our recent discussions have focused on creating effective digital marketing campaigns and optimizing online marketing channels. William prefers email communication for strategic planning updates on digital campaigns and enjoys attending digital marketing conferences. He has expertise in online advertising, search engine marketing, and social media strategy. William's digital insights and analytical skills significantly contribute to the success of our digital marketing initiatives.",
    "meeting_history": ["2022-04-15", "2022-04-30", "2022-05-15"],
    "category": "potential client"
  },
  {
    "first_name": "Ava",
    "last_name": "Jones",
    "email": "ava.jones@example.com",
    "phone_number": "555-999-0000",
    "company": "Digital Solutions Co.",
    "position": "Digital Marketing Specialist",
    "location": "Los Angeles, CA",
    "notes": "Ava is a Digital Marketing Specialist at Digital Solutions Co. Our recent collaborations have focused on creating engaging digital marketing campaigns and optimizing online advertising strategies. Ava prefers scheduled video calls for in-depth discussions on digital marketing trends and enjoys attending digital marketing conferences. She has expertise in social media marketing, content creation, and online brand building. Ava's creativity and strategic thinking significantly contribute to the success of our digital marketing projects.",
    "meeting_history": ["2022-04-20", "2022-05-05", "2022-05-20"],
    "category": "potential client"
  },
  {
    "first_name": "Sophie",
    "last_name": "Miller",
    "email": "sophie.miller@example.com",
    "phone_number": "555-888-9999",
    "company": "TechInnovate Marketing",
    "position": "Digital Marketing Specialist",
    "location": "Miami, FL",
    "notes": "Sophie is a dedicated Digital Marketing Specialist at TechInnovate Marketing. Our recent collaborations have focused on creating impactful digital marketing campaigns and enhancing online presence. Sophie prefers direct messaging for quick updates on marketing strategies and enjoys attending digital marketing webinars. She has expertise in online advertising, email marketing, and social media strategy. Sophie's attention to detail and creative approach significantly contribute to the success of our digital marketing initiatives.",
    "meeting_history": ["2022-05-01", "2022-05-15", "2022-05-30"],
    "category": "potential client"
  }]
